/**
 * Telegram Bot & API Configuration
 * Sensitive market-data credentials must come from server-side environment variables.
 * No secrets are stored in the repository.
 */

const env = process.env;

export const DEFAULT_BOT_TOKEN = env.BOT_TOKEN || '';

export const BOT_CONFIG = {
  token: env.BOT_TOKEN || '',
  botUsername: env.BOT_USERNAME || 'Modasr_Arzbot',
  adminId: parseInt(env.ADMIN_ID || '0', 10),
  nobitexApi: env.NOBITEX_API_URL || 'https://api.nobitex.ir/market/stats',
  fastApiUrl: env.FASTCREAT_CRYPTO_API_URL || 'https://api.fast-creat.ir/nobitex/v2',
  goldApiUrl: env.FASTCREAT_GOLD_API_URL || 'https://api.fast-creat.ir/gold',
  nobitexDirectApi: env.NOBITEX_DIRECT_API_URL || 'https://api.nobitex.ir/market/stats',
};

export const UNIFIED_DEFAULT_MARKET = {
  tetherToman: 267632,
  dollarToman: 267632,
  gold18Toman: 26364300,
  gold24Toman: 35152100,
  mesghalToman: 114195000,
  sekeEmamiToman: 271910000,
  sekeBaharToman: 264220000,
  nimToman: 143460000,
  robToman: 77230000,
  geramiToman: 38150000,
  silverToman: 538510,
  onsUsd: 4163.24,
  brentUsd: 101.08,
};

export const MANUAL_ALIASES: Record<string, string> = {
  // Oil & Energy
  'نفت': 'oil_brent',
  'نفت برنت': 'oil_brent',
  'brent': 'oil_brent',
  'oil': 'oil_brent',
  'نفت خام': 'oil_wti',
  'wti': 'oil_wti',
  'گاز': 'gas',
  'گاز طبیعی': 'gas',

  // Gold, Silver & Coins
  'طلا': 'gold',
  'gold': 'gold',
  'طلا گرمی': 'gold',
  'یک گرم طلا': 'gold',
  'گرم طلا': 'gold',
  'مظنه': 'gold',
  'مثقال': 'gold',
  'طلای ۱۸ عیار': 'gold',
  'طلا 18': 'gold',
  'طلای 18': 'gold',
  'طلا ۲۴': 'gold_24k',
  'طلای ۲۴ عیار': 'gold_24k',
  'طلا 24': 'gold_24k',
  'دست دوم': 'gold_used',
  'طلای دست دوم': 'gold_used',
  'آبشده': 'gold_melted',
  'انس طلا': 'gold_ounce',
  'انس': 'gold_ounce',
  'نقره': 'silver',
  'silver': 'silver',
  'انس نقره': 'silver_ounce',
  'سکه': 'seke_emami',
  'سکه امامی': 'seke_emami',
  'سکه بهار آزادی': 'seke_bahar',
  'سکه بهار': 'seke_bahar',
  'تمام سکه': 'seke_bahar',
  'سکه طرح جدید': 'seke_emami',
  'سکه طرح قدیم': 'seke_bahar',
  'نیم سکه': 'seke_nim',
  'ربع سکه': 'seke_rob',
  'سکه گرمی': 'seke_gerami',

  // Fiat Currencies (واحدهای پول ملی)
  'دلار': 'usd',
  'دلار آمریکا': 'usd',
  'اسکناس دلار': 'usd',
  'دلار تهران': 'usd',
  'دلار سبزه میدان': 'usd',
  'دلار هرات': 'usd',
  'dollar': 'usd',
  'usd': 'usd',

  // Cryptocurrencies: Tether Stablecoin (رمزارز تتر)
  'تتر': 'usdt',
  'tether': 'usdt',
  'usdt': 'usdt',
  'تتر دیجیتال': 'usdt',
  'تتر صرافی': 'usdt',
  'یورو': 'eur',
  'eur': 'eur',
  'درهم': 'aed',
  'درهم امارات': 'aed',
  'aed': 'aed',
  'پوند': 'gbp',
  'پوند انگلیس': 'gbp',
  'gbp': 'gbp',
  'لیر': 'try',
  'لیر ترکیه': 'try',
  'try': 'try',
  'یوان': 'cny',
  'یوان چین': 'cny',
  'cny': 'cny',
  'دلار کانادا': 'cad',
  'cad': 'cad',
  'دلار استرالیا': 'aud',
  'aud': 'aud',
  'فرانک': 'chf',
  'فرانک سوئیس': 'chf',
  'chf': 'chf',

  // Top Cryptos
  'تون': 'ton',
  'ton': 'ton',
  'toncoin': 'ton',
  'تون کوین': 'ton',
  'ترون': 'trx',
  'trx': 'trx',
  'اتریوم': 'eth',
  'eth': 'eth',
  'اتریوم کلاسیک': 'etc',
  'etc': 'etc',
  'بیت کوین': 'btc',
  'بیتکوین': 'btc',
  'btc': 'btc',
  'بیت کوین کش': 'bch',
  'bch': 'bch',
  'بایننس کوین': 'bnb',
  'bnb': 'bnb',
  'ریپل': 'xrp',
  'xrp': 'xrp',
  'لایت کوین': 'ltc',
  'ltc': 'ltc',
  'مونرو': 'xmr',
  'xmr': 'xmr',
  'دوج کوین': 'doge',
  'دوج': 'doge',
  'doge': 'doge',
  'شیبا': 'shib',
  'shib': 'shib',
  'شیبا اینو': 'shib',
  'پپ': 'pepe',
  'پپه': 'pepe',
  'pepe': 'pepe',
  'نات کوین': 'not',
  'نات': 'not',
  'not': 'not',
  'داگز': 'dogs',
  'dogs': 'dogs',
  'همستر': 'hmstr',
  'hmstr': 'hmstr',
  'کتیزن': 'cati',
  'cati': 'cati',
  'ماژور': 'major',
  'major': 'major',
  'سویی': 'sui',
  'sui': 'sui',
  'سولانا': 'sol',
  'sol': 'sol',
  'solana': 'sol',
  'پالیگان': 'pol',
  'pol': 'pol',
  'matic': 'pol',
  'استلار': 'xlm',
  'xlm': 'xlm',
  'کاردانو': 'ada',
  'ada': 'ada',
  'چین لینک': 'link',
  'link': 'link',
  'یونی سواپ': 'uni',
  'uni': 'uni',
  'دای': 'dai',
  'dai': 'dai',
  'پولکادات': 'dot',
  'dot': 'dot',
  'آوه': 'aave',
  'aave': 'aave',
  'اکسی': 'axs',
  'axs': 'axs',
  'دیسنترالند': 'mana',
  'mana': 'mana',
  'سندباکس': 'sand',
  'sand': 'sand',
  'آوالانچ': 'avax',
  'avax': 'avax',
  'یو اس دی کوین': 'usdc',
  'usdc': 'usdc',
  'استپن': 'gmt',
  'gmt': 'gmt',
  'میکر': 'mkr',
  'mkr': 'mkr',
  'اتم': 'atom',
  'atom': 'atom',
  'گراف': 'grt',
  'grt': 'grt',
  'بت': 'bat',
  'bat': 'bat',
  'نیر پروتکل': 'near',
  'near': 'near',
  'ایپ کوین': 'ape',
  'ape': 'ape',
  'کوانت': 'qnt',
  'qnt': 'qnt',
  'چیلیز': 'chz',
  'chz': 'chz',
  'گالا': 'egala',
  'egala': 'egala',
  'الگورند': 'algo',
  'algo': 'algo',
  'هدرا': 'hbar',
  'hbar': 'hbar',
  'وان ایچ نتورک': '1inch',
  '1inch': '1inch',
  'یرن فایننس': 'yfi',
  'yfi': 'yfi',
  'فلو': 'flow',
  'flow': 'flow',
  'فلوکی': 'floki',
  'floki': 'floki',
  'بونک': 'bonk',
  'bonk': 'bonk',
  'ویف': 'wif',
  'wif': 'wif',
  'کاسپا': 'kas',
  'kas': 'kas',
  'رندر': 'render',
  'render': 'render',
  'آپتوس': 'apt',
  'apt': 'apt',
  'سلستیا': 'tia',
  'tia': 'tia',
  'سینتتیکس': 'snx',
  'snx': 'snx',
  'انجین کوین': 'enj',
  'enj': 'enj',
  'کرو دائو توکن': 'crv',
  'crv': 'crv',
  'فایل کوین': 'fil',
  'fil': 'fil',
  'رپد بیت کوین': 'wbtc',
  'wbtc': 'wbtc',
  'لیدو دائو': 'ldo',
  'ldo': 'ldo',
  'دی وای دی ایکس': 'dydx',
  'dydx': 'dydx',
  'اپتاس': 'apt',
  'مسک نتورک': 'mask',
  'mask': 'mask',
  'کامپاند': 'comp',
  'comp': 'comp',
  'بالانسر': 'bal',
  'bal': 'bal',
  'لوپرینگ': 'lrc',
  'lrc': 'lrc',
  'لایوپیر': 'lpt',
  'lpt': 'lpt',
  'اتریوم نیم سرویس': 'ens',
  'ens': 'ens',
  'سوشی سواپ': 'sushi',
  'sushi': 'sushi',
  'ای پی آی 3': 'api3',
  'api3': 'api3',
  'هارمونی': 'one',
  'one': 'one',
  'گولم': 'glm',
  'glm': 'glm',
  'پیمان': 'pmn',
  'pmn': 'pmn',
  'دائو میکر': 'dao',
  'dao': 'dao',
  'سیویک': 'cvc',
  'cvc': 'cvc',
  'نومریر': 'nmr',
  'nmr': 'nmr',
  'استورج': 'storj',
  'storj': 'storj',
  'استاتوس': 'snt',
  'snt': 'snt',
  'آراگون': 'ant',
  'ant': 'ant',
  'زیرو ایکس': 'zrx',
  'zrx': 'zrx',
  'اسموث لاو پوشن': 'slp',
  'slp': 'slp',
  'مولتی ورس ایکس': 'egld',
  'egld': 'egld',
  'ایموتبل ایکس': 'imx',
  'imx': 'imx',
  'بلر': 'blur',
  'blur': 'blur',
  '100 هزار فلوکی': '100k_floki',
  '100k_floki': '100k_floki',
  '1 میلیارد بیبی دوج': '1b_babydoge',
  '1b_babydoge': '1b_babydoge',
  '1 میلیون ایپ ان اف تی': '1m_nft',
  '1m_nft': '1m_nft',
  '1 میلیون بیت تورنت': '1m_btt',
  '1m_btt': '1m_btt',
  'ترشولد': 't',
  't': 't',
  'سلر نتورک': 'celr',
  'celr': 'celr',
  'اربیتروم': 'arb',
  'arb': 'arb',
  'مجیک': 'magic',
  'magic': 'magic',
  'جی ام ایکس': 'gmx',
  'gmx': 'gmx',
  'بند': 'band',
  'band': 'band',
  'کانوکس فایننس': 'cvx',
  'cvx': 'cvx',
  'اس اس وی نتوورک': 'ssv',
  'ssv': 'ssv',
  'مرژبل دیتا': 'mdt',
  'mdt': 'mdt',
  'او ام جی نتورک': 'omg',
  'omg': 'omg',
  'ورلد کوین': 'wld',
  'wld': 'wld',
  'رادیانت کپیتال': 'rdnt',
  'rdnt': 'rdnt',
  'جاست': 'jst',
  'jst': 'jst',
  'بیکو': 'bico',
  'bico': 'bico',
  'وو نتورک': 'woo',
  'woo': 'woo',
  'اسکیل': 'skl',
  'skl': 'skl',
  'گلکس': 'gal',
  'gal': 'gal',
  'سینگولاریتی نت': 'agix',
  'agix': 'agix',
  'فچ ای آی': 'fet',
  'fet': 'fet',
  'فانتوم': 's',
  'ftm': 's',
  's': 's',
};
